application: enablecors
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /
  script: enablecors.application

- url: /assets/js
  mime_type: application/javascript
  static_dir: assets/js

- url: /assets/js-cors
  mime_type: application/javascript
  static_dir: assets/js-cors
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /assets/css
  mime_type: text/css
  static_dir: assets/css

- url: /assets/images
  static_dir: assets/images

- url: /robots.txt
  static_files: assets/seo/robots.txt
  upload: assets/seo/robots.txt

- url: /humans.txt
  static_files: assets/seo/humans.txt
  upload: assets/seo/humans.txt

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
